version: '3.1'
services:

  frontend-nginx:
    build:
      context: ./frontend/docker
      dockerfile: nginx.docker
    volumes:
    - ./frontend:/var/www/frontend
    ports:
    - "8081:80"

  frontend-nodejs:
    image: node:11.4.0-alpine
    volumes:
    - ./frontend:/var/www/frontend
    working_dir: /var/www/frontend
    tty: true

  backend-nginx:
    build:
      context: ./backend/docker
      dockerfile: nginx.docker
    volumes:
    - ./backend:/var/www/backend
    ports:
    - "8082:80"

  backend-php-fpm:
    build:
      context: ./backend/docker
      dockerfile: fpm.docker
    volumes:
    - ./backend:/var/www/backend
    - ./backend/storage:/var/www/backend/storage

  backend-php-cli:
    build:
      context: ./backend/docker
      dockerfile: php-cli.docker
    volumes:
    - ./backend:/var/www/backend
    working_dir: /var/www/backend
    tty: true

  backend-mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: filehosting
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./backend/docker/config/filehosting.sql:/docker-entrypoint-initdb.d/filehosting.sql
    ports:
    - "8083:3306"

  backend-sphinx:
    build:
      context: ./backend/docker
      dockerfile: sphinx.docker
    ports:
    - 127.0.0.1:8084:36307